### ISSUE TITLE
感谢分享，有个小建议

### ISSUE THREAD

**Issue by xymeng16** [yqs112358/TombedAppsMonitor#1]
感谢作者的工作！

一个小建议，可以只获取Android应用（ps -A | **grep u0_a** | grep -E 'refrigerator|do_freezer|signal'），目前应用列表会将很多不需要用户关注的Native/系统进程也列出来，同时头像也会错乱，比如很多时候zygote/app_process休眠时会被列在app里同时附着一个微信/Bilibili的图标，无伤大雅但有些让人费解。

我这没有安卓编译环境不好开PR，如果您觉得有必要就直接加上吧，辛苦！

**Comment by yqs112358** [comment]
感谢建议🥰等会有空我改一下

**Comment by yqs112358** [comment]
修了一下bug，麻烦大佬试用一下还有无问题，OK的话我发个新版
[TombedMonitor-0.1.2.zip](https://github.com/yqs112358/TombedAppsMonitor/files/12336028/TombedMonitor-0.1.2.zip)

**Comment by xymeng16** [comment]
> 修了一下bug，麻烦大佬试用一下还有无问题，OK的话我发个新版 [TombedMonitor-0.1.2.zip](https://github.com/yqs112358/TombedAppsMonitor/files/12336028/TombedMonitor-0.1.2.zip)

试用了一下，问题完美解决，感谢作者这么快的响应！

**Comment by yqs112358** [comment]
OK😋
